[package]
name = "umm_derive"
version = "0.1.0"
edition = "2024"


[lib]
proc-macro = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "2.0.15", features = ["full", "extra-traits"] }
quote = "1.0.27"
"proc-macro-error" = "1.0.4"
